# Generated by Django 4.2.6 on 2023-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-14 12:56:30.917018+00:00'),
            preserve_default=False,
        ),
    ]
