# Generated by Django 4.2.6 on 2023-10-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('avatar', models.ImageField(upload_to='')),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
