# Generated by Django 4.2.6 on 2023-10-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='workers',
            name='message',
        ),
    ]
